using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace OrgStructureApi.Migrations.AutoGenerated
{
    /// <inheritdoc />
    public partial class AddUniqueIndexesAndRestrictEmployeeCompany : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Employees_Companies_CompanyId",
                table: "Employees");

            migrationBuilder.DropIndex(
                name: "IX_Projects_DivisionId",
                table: "Projects");

            migrationBuilder.DropIndex(
                name: "IX_Divisions_CompanyId",
                table: "Divisions");

            migrationBuilder.DropIndex(
                name: "IX_Departments_ProjectId",
                table: "Departments");

            migrationBuilder.AlterColumn<string>(
                name: "Phone",
                table: "Employees",
                type: "nvarchar(450)",
                nullable: false,
                oldClrType: typeof(string),
                oldType: "nvarchar(max)");

            migrationBuilder.AlterColumn<string>(
                name: "Email",
                table: "Employees",
                type: "nvarchar(450)",
                nullable: false,
                oldClrType: typeof(string),
                oldType: "nvarchar(max)");
            migrationBuilder.CreateIndex(
                name: "IX_Projects_DivisionId_Code",
                table: "Projects",
                columns: new[] { "DivisionId", "Code" },
                unique: true);

            // Deduplicate employee emails: append +dup{Id} before @ for duplicate emails
            migrationBuilder.Sql(@"
WITH cte AS (
    SELECT Id, Email, ROW_NUMBER() OVER (PARTITION BY Email ORDER BY Id) AS rn
    FROM Employees
    WHERE Email IS NOT NULL
)
UPDATE e
SET Email = CONCAT(LEFT(e.Email, CHARINDEX('@', e.Email) - 1), '+dup', e.Id, SUBSTRING(e.Email, CHARINDEX('@', e.Email), 8000))
FROM Employees e
INNER JOIN cte c ON e.Id = c.Id
WHERE c.rn > 1;
");

            migrationBuilder.CreateIndex(
                name: "IX_Employees_Email",
                table: "Employees",
                column: "Email",
                unique: true);

            // Deduplicate employee phones: append -{Id} for duplicate phones
            migrationBuilder.Sql(@"
WITH cte AS (
    SELECT Id, Phone, ROW_NUMBER() OVER (PARTITION BY Phone ORDER BY Id) AS rn
    FROM Employees
    WHERE Phone IS NOT NULL
)
UPDATE e
SET Phone = CONCAT(e.Phone, '-', e.Id)
FROM Employees e
INNER JOIN cte c ON e.Id = c.Id
WHERE c.rn > 1;
");

            migrationBuilder.CreateIndex(
                name: "IX_Employees_Phone",
                table: "Employees",
                column: "Phone",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_Divisions_CompanyId_Code",
                table: "Divisions",
                columns: new[] { "CompanyId", "Code" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_Departments_ProjectId_Code",
                table: "Departments",
                columns: new[] { "ProjectId", "Code" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_Companies_Code",
                table: "Companies",
                column: "Code",
                unique: true);

            migrationBuilder.AddForeignKey(
                name: "FK_Employees_Companies_CompanyId",
                table: "Employees",
                column: "CompanyId",
                principalTable: "Companies",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Employees_Companies_CompanyId",
                table: "Employees");

            migrationBuilder.DropIndex(
                name: "IX_Projects_DivisionId_Code",
                table: "Projects");

            migrationBuilder.DropIndex(
                name: "IX_Employees_Email",
                table: "Employees");

            migrationBuilder.DropIndex(
                name: "IX_Employees_Phone",
                table: "Employees");

            migrationBuilder.DropIndex(
                name: "IX_Divisions_CompanyId_Code",
                table: "Divisions");

            migrationBuilder.DropIndex(
                name: "IX_Departments_ProjectId_Code",
                table: "Departments");

            migrationBuilder.DropIndex(
                name: "IX_Companies_Code",
                table: "Companies");

            migrationBuilder.AlterColumn<string>(
                name: "Phone",
                table: "Employees",
                type: "nvarchar(max)",
                nullable: false,
                oldClrType: typeof(string),
                oldType: "nvarchar(450)");

            migrationBuilder.AlterColumn<string>(
                name: "Email",
                table: "Employees",
                type: "nvarchar(max)",
                nullable: false,
                oldClrType: typeof(string),
                oldType: "nvarchar(450)");

            migrationBuilder.CreateIndex(
                name: "IX_Projects_DivisionId",
                table: "Projects",
                column: "DivisionId");

            migrationBuilder.CreateIndex(
                name: "IX_Divisions_CompanyId",
                table: "Divisions",
                column: "CompanyId");

            migrationBuilder.CreateIndex(
                name: "IX_Departments_ProjectId",
                table: "Departments",
                column: "ProjectId");

            migrationBuilder.AddForeignKey(
                name: "FK_Employees_Companies_CompanyId",
                table: "Employees",
                column: "CompanyId",
                principalTable: "Companies",
                principalColumn: "Id");
        }
    }
}
